stages:
  fetch_data:
    cmd: python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    outs:
      - data/raw/
  
  preprocess_data:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/
    outs:
      - data/processed/
  
  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/
    outs:
      - models/
